# Generated by Django 5.0.2 on 2024-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_ranobe_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ranobe_file',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
