# Generated by Django 5.0.2 on 2024-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_ranobe_file_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
