# Generated by Django 5.0.2 on 2024-03-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='book.genre'),
        ),
    ]
