# Generated by Django 5.0.2 on 2024-03-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book2_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book2',
            name='author',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book2',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book2',
            name='title',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
