# Generated by Django 5.0.2 on 2024-03-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_book2_author_alter_book2_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_chapters', models.CharField(editable=False, max_length=100)),
                ('chapters', models.TextField(editable=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book2')),
            ],
        ),
    ]
