# Generated by Django 5.0.2 on 2024-03-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Chapter',
        ),
    ]
