# Generated by Django 5.0.2 on 2024-03-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_delete_book_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
