# Generated by Django 5.0.2 on 2024-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_book2_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='file',
            field=models.FileField(unique=True, upload_to='media/file', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='photo',
            field=models.ImageField(unique=True, upload_to='media/photo', verbose_name='фото'),
        ),
    ]
