# Generated by Django 5.0.2 on 2024-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book2_file_alter_book2_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='title',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='название'),
        ),
    ]
